.TH SMALNETS 1 "2026-07-08" "Smalnets" "User Commands"
.SH NAME
smalnets \- Smalnets Router Configuration Tool
.SH SYNOPSIS
.B smalnets
[\fB\-\-version\fR] [\fB\-v\fR]
.SH DESCRIPTION
Smalnets Config Tool is the official desktop application for configuring and
managing MikroTik routers. Provides connection testing, password management,
VPN/WireGuard setup, GenieACS integration, RADIUS NAS registration, and
hotspot provisioning.
.SH OPTIONS
.TP
.B \-\-version, \-v
Display the version of Smalnets Config Tool and exit.
.SH FILES
.TP
.I ~/.config/smalnets/preferences.json
User preferences file containing theme settings and other configuration.
.SH BUGS
Report bugs at https://github.com/jetsup/insta-billing/issues
.SH AUTHOR
Smalnets Team
.SH COPYRIGHT
MIT License
